# Generated by Django 3.2.9 on 2021-12-20 10:39

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('about_author', models.TextField()),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('isbn', models.CharField(blank=True, default='8353977677516', max_length=13, null=True, unique=True)),
                ('price', models.FloatField(help_text='in Dollar ($)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.PositiveIntegerField(blank=True, default=4, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='bookstore.author')),
                ('category', models.ManyToManyField(related_name='category', to='category.Category')),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
